#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart