#!/usr/bin/env bash
# custom 404 page
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html
TEXT="location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n"
sudo sed -i "42i $TEXT" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
CUSTOM="error_page 404 /404.html;\nlocation = \404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx start